# Generated by Django 6.0.3 on 2026-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_alter_item_seller"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="marketplace_images/"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
