# Generated by Django 6.0.3 on 2026-03-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="year",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
