# Generated by Django 6.0.3 on 2026-03-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="department",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_pic",
        ),
        migrations.RemoveField(
            model_name="user",
            name="year",
        ),
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="profiles/default.png", upload_to="profiles/"
            ),
        ),
    ]
