# Generated by Django 6.0.3 on 2026-03-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_user_bio_remove_user_department_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("alumni", "Alumni"),
                    ("teacher", "Teacher"),
                    ("admin", "Admin"),
                ],
                max_length=10,
            ),
        ),
    ]
