# Generated by Django 6.0.3 on 2026-03-21 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collaboration", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="joined_projects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
